export const LOGIN_STAFF = "LOGIN_STAFF";
export const BASE_URL = "https://slldm.com";
//export const BASE_URL = "https://solarcrm.dashandots.tech";

export const initialState = {};

export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const SEARCH_PROJECTS = "SEARCH_PROJECTS";
export const VIEW_PROJECT = "VIEW_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const COUNT_PROJECTS = "COUNT_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const CHANGE_PROJECT_STATUS = "CHANGE_PROJECT_STATUS";
export const SET_PROJECT_TYPE = "SET_PROJECT_TYPE"

export const VIEW_TASK = "VIEW_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const INITIALIZE_TASKS = "INITIALIZE_TASKS";

export const FETCH_SITES = "FETCH_SITES";
export const VIEW_SITE = "VIEW_SITE";
export const UPDATE_SITE = "UPDATE_SITE";
export const ADD_SITE = "ADD_SITE";
export const SEARCH_SITE = "SEARCH_SITE";

export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const VIEW_INVENTORY = "VIEW_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const COUNT_INVENTORY = "COUNT_INVENTORY";

// VIEW_VENDOR, UPDATE_VENDOR, SEARCH_VENDOR, COUNT_VENDOR;

export const VIEW_VENDOR = "VIEW_VENDOR";
export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const SEARCH_VENDOR = "SEARCH_VENDOR";
export const COUNT_VENDOR = "COUNT_VENDOR";
export const GET_ALL_VENDORS = "GET_ALL_VENDORS";

export const GET_PENDING_STREETLIGHTS = "GET_PENDING_STREETLIGHTS";
export const TOTAL_PENDING_STREETLIGHT = "SET_TOTAL_PENDING_STREETLIGHT";
export const GET_SURVEYED_STREETLIGHTS = "GET_SURVEYED_STREETLIGHTS";
export const TOTAL_SURVEYED_STREETLIGHTS = "TOTAL_SURVEYED_STREETLIGHTS";
export const GET_INSTALLED_STREETLIGHTS = "GET_INSTALLED_STREETLIGHTS";
export const TOTAL_INSTALLED_STREETLIGHTS = "TOTAL_INSTALLED_STREETLIGHTS";
export const GET_ALL_REJECTED_STREETLIGHTS = "GET_ALL_REJECTED_STREETLIGHTS";

export const SET_BILL_DATA = "SET_BILL_DATA";
