export const LOGIN_STAFF = "LOGIN_STAFF";

export const initialState = {
  userId: null,
};

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const SEARCH_PROJECTS = 'SEARCH_PROJECTS';
export const VIEW_PROJECT = 'VIEW_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const COUNT_PROJECTS = 'COUNT_PROJECTS';
export const CHANGE_PROJECT_STATUS = 'CHANGE_PROJECT_STATUS';

export const VIEW_TASK = 'VIEW_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const INITIALIZE_TASKS = 'INITIALIZE_TASKS';

export const VIEW_SITE = "VIEW_SITE";
export const SEARCH_SITE = "SEARCH_SITE";

export const VIEW_INVENTORY = 'VIEW_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const SEARCH_INVENTORY = 'SEARCH_INVENTORY';
export const COUNT_INVENTORY = 'COUNT_INVENTORY';

VIEW_VENDOR, UPDATE_VENDOR, SEARCH_VENDOR, COUNT_VENDOR

export const VIEW_VENDOR = 'VIEW_VENDOR';
export const UPDATE_VENDOR = 'UPDATE_VENDOR';
export const SEARCH_VENDOR = 'SEARCH_VENDOR';
export const COUNT_VENDOR = 'COUNT_VENDOR';