name: "Build Android App"
run-name: ${{ github.actor }} is building apk using Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean up before build
        run: |
          rm -rf ./node_modules
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run npm install
        run: npm install

      - name: Generate Android Bundle
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build App
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
